blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Channel
    url: https://discord.com/invite/aUTgv2Yc4u
    about: The discord channel of PurpleDye

  - name: 💬 Support Discord Channel
    url: https://discord.com/channels/937789590390071346/937789590998237272
    about: The support channel of PurpleDye's discord.
